<?php
// download_report.php

ob_start();

require_once('../fpdf186/fpdf.php');
require_once '../dbconnect.php';

// -----------------------------------
// VALIDATE PATIENT CODE
// -----------------------------------

if (!isset($_GET['patient_code'])) {
    die("Patient code is required.");
}

$patient_code = trim($_GET['patient_code']);

// -----------------------------------
// FETCH PATIENT DETAILS
// -----------------------------------

$patientQuery = "SELECT * FROM patients WHERE patient_code = ?";

$stmt1 = $conn->prepare($patientQuery);
$stmt1->bind_param("s", $patient_code);
$stmt1->execute();

$patientResult = $stmt1->get_result();

if ($patientResult->num_rows === 0) {
    die("Patient not found.");
}

$patient = $patientResult->fetch_assoc();

// -----------------------------------
// FETCH LATEST VITALS
// -----------------------------------

$vitalsQuery = "
    SELECT * 
    FROM vitals 
    WHERE patient_code = ? 
    ORDER BY recorded_at DESC 
    LIMIT 1
";

$stmt2 = $conn->prepare($vitalsQuery);
$stmt2->bind_param("s", $patient_code);
$stmt2->execute();

$vitalsResult = $stmt2->get_result();

$vitals = $vitalsResult->fetch_assoc() ?? [];

// -----------------------------------
// PDF CLASS
// -----------------------------------

class PDF extends FPDF
{
    function Header()
    {
        // OUTER BORDER
        $this->SetLineWidth(0.8);
        $this->Rect(10, 10, 190, 277);

        // LOGO
        // Put logo.png inside same folder
        $this->Image('../Assets/CareSyncLogo.png', 15, 15, 20);

        // HOSPITAL TITLE
        $this->SetFont('Arial', 'B', 16);
        $this->SetTextColor(20, 20, 20);
        $this->SetXY(42, 18);

        $this->Cell(120, 8, 'CareSync Healthcare', 0, 1);

        // ADDRESS
        $this->SetFont('Arial', '', 10);
        $this->SetX(42);

        $this->Cell(
            120,
            6,
            'Bhubaneswar, Odisha - 751021',
            0,
            1
        );

        // CONTACT
        $this->SetX(42);

        $this->Cell(
            120,
            6,
            'Phone: +91 9876543210',
            0,
            1
        );

        // HEADER LINE
        $this->SetDrawColor(0, 97, 255);
        $this->SetLineWidth(1);

        $this->Line(10, 48, 190, 48);

        // REPORT TITLE
        $this->SetFont('Arial', 'B', 14);
        $this->SetXY(70, 55);

        $this->Cell(70, 10, 'PATIENT HEALTH REPORT', 0, 1, 'C');
    }

    function Footer()
    {
        $this->SetY(-22);

        // FOOTER LINE
        $this->SetDrawColor(0, 97, 255);
        $this->Line(10, 275, 190, 275);

        // FOOTER TEXT
        $this->SetFont('Arial', '', 10);

        $this->Cell(
            0,
            10,
            'Generated by CareSync',
            0,
            0,
            'C'
        );
    }
}

// -----------------------------------
// CREATE PDF
// -----------------------------------

$pdf = new PDF('P', 'mm', 'A4');

$pdf->AddPage();

$pdf->SetAutoPageBreak(true, 20);

// -----------------------------------
// PATIENT DETAILS
// -----------------------------------

$pdf->SetFont('Arial', 'B', 12);

$pdf->SetXY(15, 75);

$pdf->Cell(180, 8, 'Patient Information', 0, 1);

$pdf->SetFont('Arial', '', 11);

$y = 88;

// LEFT COLUMN

$pdf->SetXY(18, $y);
$pdf->Cell(85, 8, 'Full Name: ' . $patient['full_name']);

$pdf->SetXY(110, $y);
$pdf->Cell(70, 8, 'Patient Code: ' . $patient['patient_code']);

$y += 10;

$pdf->SetXY(18, $y);
$pdf->Cell(85, 8, 'Email: ' . $patient['email']);

$pdf->SetXY(110, $y);
$pdf->Cell(70, 8, 'Mobile: ' . $patient['mobile']);

$y += 10;

$pdf->SetXY(18, $y);
$pdf->Cell(85, 8, 'Gender: ' . $patient['gender']);

$pdf->SetXY(110, $y);
$pdf->Cell(70, 8, 'Blood Group: ' . $patient['blood_group']);

// SECTION LINE

$pdf->SetDrawColor(220, 220, 220);

$pdf->Line(15, 120, 190, 120);

// -----------------------------------
// VITALS SECTION
// -----------------------------------

$pdf->SetFont('Arial', 'B', 12);

$pdf->SetXY(15, 128);

$pdf->Cell(180, 8, 'Latest Vital Information', 0, 1);

$pdf->SetFont('Arial', '', 11);

$y = 142;

// ROW 1

$pdf->SetXY(18, $y);
$pdf->Cell(
    85,
    8,
    'Attendee Code: ' .
        ($vitals['attendee_code'] ?? 'N/A')
);

$pdf->SetXY(110, $y);
$pdf->Cell(
    70,
    8,
    'Blood Pressure: ' .
        ($vitals['blood_pressure'] ?? 'N/A') . ' mmHg'
);

// ROW 2

$y += 12;

$pdf->SetXY(18, $y);
$pdf->Cell(
    85,
    8,
    'Heart Rate: ' .
        ($vitals['heart_rate'] ?? 'N/A') . ' bpm'
);

$pdf->SetXY(110, $y);
$pdf->Cell(
    70,
    8,
    'Temperature: ' .
        ($vitals['temperature'] ?? 'N/A') . ' '. chr(176) .'C'
);

// ROW 3

$y += 12;

$pdf->SetXY(18, $y);
$pdf->Cell(
    85,
    8,
    'Respiratory Rate: ' .
        ($vitals['respiratory_rate'] ?? 'N/A') . ' /min'
);

$pdf->SetXY(110, $y);
$pdf->Cell(
    70,
    8,
    'Oxygen Saturation(SPO2): ' .
        ($vitals['oxygen_saturation'] ?? 'N/A') . '%'
);

// ROW 4

$y += 12;

$pdf->SetXY(18, $y);
$pdf->Cell(
    85,
    8,
    'Blood Sugar: ' .
        ($vitals['blood_sugar'] ?? 'N/A'). ' mg/dL'
);

$pdf->SetXY(110, $y);
$pdf->Cell(
    70,
    8,
    'Weight: ' .
        ($vitals['weight_kg'] ?? 'N/A') . ' kg'
);

// ROW 5

$y += 12;

$pdf->SetXY(18, $y);
$pdf->Cell(
    85,
    8,
    'Height: ' .
        ($vitals['height_cm'] ?? 'N/A') . ' cm'
);

// -----------------------------------
// NOTES
// -----------------------------------

$y += 18;

$pdf->SetXY(18, $y);

$pdf->SetFont('Arial', 'B', 11);

$pdf->Cell(40, 8, 'Clinical Notes:');

$pdf->SetFont('Arial', '', 11);

$pdf->SetXY(18, $y + 10);

$notes = $vitals['notes'] ?? 'No notes available.';

$pdf->MultiCell(
    165,
    7,
    $notes
);

// -----------------------------------
// REPORT DATE
// -----------------------------------

$pdf->SetXY(18, 255);

$pdf->SetFont('Arial', '', 10);

$pdf->Cell(
    100,
    8,
    'Generated On: ' . date('d-m-Y h:i A')
);

// -----------------------------------
// DOWNLOAD PDF
// -----------------------------------

$fileName =
    'CareSync_Report_' .
    $patient['patient_code'] .
    '.pdf';

ob_end_clean();

$pdf->Output('D', $fileName);
